#!/bin/sh
# release.sh — cut an oxwrt release.
#
# One-shot workflow:
#   1. Bump the workspace version in Cargo.toml (patch|minor|major).
#   2. Walk `git log LAST_TAG..HEAD`, group commits by the
#      `<area>:` prefix that every commit in this repo uses,
#      prepend a new CHANGELOG.md section.
#   3. `cargo check --workspace` to catch a broken version bump.
#   4. Commit the bump + changelog as "release: vX.Y.Z".
#   5. Create an annotated tag `vX.Y.Z`.
#   6. Print a "what to paste on GitHub Releases" blob (just the
#      new CHANGELOG section).
#
# Usage:
#   scripts/release.sh patch                  # 0.1.1 → 0.1.2
#   scripts/release.sh minor                  # 0.1.1 → 0.2.0
#   scripts/release.sh major                  # 0.1.1 → 1.0.0
#   scripts/release.sh patch --dry-run        # show plan, don't touch anything
#
# Prerequisites:
#   - Clean working tree (no uncommitted changes). The script
#     refuses to run otherwise — you'll lose your place if the
#     bump-commit rolls in on top of unrelated edits.
#   - Running from the repo root.
#
# For production releases, CI workflow `release.yml` picks up the
# tag push and does the build+sign+publish in one go. The local
# signing block below is a fallback for operators cutting a
# release entirely off-network.
#
# See RELEASING.md for the end-to-end runbook, signing-key setup,
# and post-release verification steps.

set -eu

usage() {
    echo "usage: $0 {patch|minor|major} [--dry-run]" >&2
    exit 2
}

# ── arg parse ──
[ $# -ge 1 ] || usage
BUMP="$1"
DRY_RUN=0
case "${2:-}" in
    --dry-run) DRY_RUN=1 ;;
    "") ;;
    *) usage ;;
esac
case "$BUMP" in patch|minor|major) ;; *) usage ;; esac

# ── repo + tree checks ──
cd "$(dirname "$0")/.."
if [ ! -f Cargo.toml ]; then
    echo "release.sh: Cargo.toml not found — run from repo root" >&2
    exit 1
fi
if [ "$DRY_RUN" = 0 ] && [ -n "$(git status --porcelain)" ]; then
    echo "release.sh: working tree not clean; commit or stash first" >&2
    git status --short >&2
    exit 1
fi

# ── current version ──
# Matches the workspace table's `version = "X.Y.Z"` line. Grep-anchored
# so an accidental "version = ..." on a dep line doesn't match.
CURRENT=$(
    awk '
        /^\[workspace\.package\]/ { in_pkg=1; next }
        /^\[/ { in_pkg=0 }
        in_pkg && /^version *= *"[^"]+"/ {
            # split on `"` → ["version = ", "X.Y.Z", ""]; we want [2].
            n = split($0, parts, "\"")
            if (n >= 2) { print parts[2]; exit }
        }
    ' Cargo.toml
)
[ -n "$CURRENT" ] || { echo "release.sh: couldn't find workspace version" >&2; exit 1; }

# ── bump ──
MAJOR=$(echo "$CURRENT" | cut -d. -f1)
MINOR=$(echo "$CURRENT" | cut -d. -f2)
PATCH=$(echo "$CURRENT" | cut -d. -f3)
case "$BUMP" in
    patch) PATCH=$((PATCH + 1)) ;;
    minor) MINOR=$((MINOR + 1)); PATCH=0 ;;
    major) MAJOR=$((MAJOR + 1)); MINOR=0; PATCH=0 ;;
esac
NEW="$MAJOR.$MINOR.$PATCH"
TAG="v$NEW"

# ── commit log since last tag ──
LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || true)
if [ -n "$LAST_TAG" ]; then
    RANGE="$LAST_TAG..HEAD"
else
    RANGE="HEAD"
fi
RAW_LOG=$(git log --oneline --no-merges "$RANGE")
if [ -z "$RAW_LOG" ]; then
    echo "release.sh: no commits since ${LAST_TAG:-repo start} — nothing to release" >&2
    exit 1
fi

# ── group commits by `<area>:` prefix ──
# Each line is "<sha> <subject>"; subject is "<area>: <rest>" by
# repo convention. Unprefixed subjects collect under "misc".
GROUPED=$(
    echo "$RAW_LOG" | awk '
        {
            sha = $1
            $1 = ""
            subj = substr($0, 2)
            n = index(subj, ": ")
            if (n > 0) {
                area = substr(subj, 1, n - 1)
                msg = substr(subj, n + 2)
            } else {
                area = "misc"
                msg = subj
            }
            # Fold whitespace in area to normalize multi-word prefixes
            # (shouldnt exist but defensive).
            gsub(/[ \t]+/, "-", area)
            entries[area] = entries[area] "- " msg " (" sha ")\n"
            if (!(area in seen)) {
                order[++n_areas] = area
                seen[area] = 1
            }
        }
        END {
            for (i = 1; i <= n_areas; i++) {
                a = order[i]
                print "### " a
                printf "%s", entries[a]
                print ""
            }
        }
    '
)

DATE=$(date -u +%Y-%m-%d)
SECTION="## [${NEW}] — ${DATE}

${GROUPED}"

# ── bootstrap CHANGELOG if missing ──
CHANGELOG_PREAMBLE="# Changelog

All notable changes to oxwrt are documented here. Follows
[Keep a Changelog](https://keepachangelog.com/en/1.1.0/) loosely:
each release is a level-2 heading dated in UTC, with commits
grouped by the \`<area>:\` prefix they carry (\`config:\`,
\`rollback:\`, \`net:\`, etc.). Commit shas in parentheses point
back at the implementing change.

Generated by \`scripts/release.sh\` — hand-editing is fine but
the script will re-sort on the next run.

"

if [ "$DRY_RUN" = 1 ]; then
    echo "==== dry run ===="
    echo "current version: $CURRENT"
    echo "new version:     $NEW"
    echo "tag:             $TAG"
    echo "commit range:    $RANGE ($(echo "$RAW_LOG" | wc -l | tr -d ' ') commits)"
    echo ""
    echo "---- CHANGELOG.md section to prepend ----"
    echo ""
    echo "$SECTION"
    echo ""
    echo "---- end ----"
    exit 0
fi

# ── bump Cargo.toml ──
# Replace ONLY the workspace.package version, not any other version=
# lines (e.g. a pinned dep that happens to match CURRENT).
python3 - "$CURRENT" "$NEW" <<'PY'
import re, sys
current, new = sys.argv[1], sys.argv[2]
with open("Cargo.toml") as f:
    src = f.read()
pat = re.compile(
    r'(\[workspace\.package\][^\[]*?version *= *")' + re.escape(current) + r'(")',
    re.DOTALL,
)
new_src, n = pat.subn(r'\g<1>' + new + r'\g<2>', src, count=1)
if n != 1:
    sys.exit(f"release.sh: failed to bump version {current} → {new} in Cargo.toml")
with open("Cargo.toml", "w") as f:
    f.write(new_src)
PY

# ── CHANGELOG ──
if [ -f CHANGELOG.md ]; then
    # Prepend under the existing preamble. Insert before the first
    # "## " heading (an existing release entry). If no such
    # heading exists yet — typical on the first post-bootstrap
    # run — append at the end after any preamble instructions.
    #
    # Why the temp file + `getline`: BSD awk (macOS) rejects
    # embedded newlines in `-v var="..."`, so the previous
    # `-v s="$SECTION"` shape worked on GNU awk but failed on
    # macOS with `awk: newline in string`. Writing $SECTION to a
    # tempfile and slurping it via `getline` sidesteps the
    # BSD-vs-GNU awk difference entirely.
    SECTION_TMP=$(mktemp -t oxwrt-changelog-section.XXXXXX)
    trap 'rm -f "$SECTION_TMP"' EXIT
    printf "%s\n" "$SECTION" > "$SECTION_TMP"
    awk -v section_path="$SECTION_TMP" '
        function slurp_section() {
            while ((getline line < section_path) > 0) {
                print line
            }
            close(section_path)
        }
        /^## / && !done {
            slurp_section()
            print ""
            done = 1
        }
        { print }
        END {
            if (!done) {
                print ""
                slurp_section()
            }
        }
    ' CHANGELOG.md > CHANGELOG.md.new
    mv CHANGELOG.md.new CHANGELOG.md
    rm -f "$SECTION_TMP"
    trap - EXIT
else
    printf "%s" "$CHANGELOG_PREAMBLE" > CHANGELOG.md
    printf "%s\n" "$SECTION" >> CHANGELOG.md
fi

# ── sanity: does the bumped workspace still resolve? ──
echo "release.sh: cargo check --workspace ..."
cargo check --workspace --offline 2>/dev/null || cargo check --workspace

# ── commit + tag ──
git add Cargo.toml Cargo.lock CHANGELOG.md
git commit -m "release: $TAG

$(echo "$GROUPED" | sed 's/^/  /')"

git tag -a "$TAG" -m "oxwrt $TAG

$(echo "$GROUPED")"

# ── optional: sign firmware artifacts if present ──
# After the tag lands, walk for firmware images across both the
# historical `build/*.{bin,img}` layout AND the imagebuilder's
# actual output path `build/imagebuilder/bin/targets/**/*-sysupgrade.bin`
# (where `make imagebuilder-image` drops artifacts). Emit a
# detached .sig next to each via `oxctl --sign`. Skipped
# silently when no image is present (source-only release, or
# the CI workflow is doing the image build).
#
# For CI-driven releases, `.github/workflows/release.yml` builds
# + signs with `OXWRT_SIGNING_KEY` from repo secrets. This local
# block is the offline fallback — see RELEASING.md for setup.
IMAGES=$(
    { ls build/*.bin build/*.img 2>/dev/null || true; } \
    | grep -v '\.sig$' || true
)
if [ -d build/imagebuilder/bin ]; then
    FOUND_IB=$(find build/imagebuilder/bin -type f \
        \( -name '*.bin' -o -name '*.img' \) ! -name '*.sig' 2>/dev/null || true)
    IMAGES=$(printf "%s\n%s" "$IMAGES" "$FOUND_IB" | sed '/^$/d')
fi
if [ -n "$IMAGES" ]; then
    if [ -n "${OXWRT_SIGNING_KEY_PATH:-}${OXWRT_SIGNING_KEY:-}" ]; then
        if [ -x target/release/oxctl ]; then
            echo "$IMAGES" | while IFS= read -r img; do
                [ -f "$img" ] || continue
                echo "release.sh: signing $img ..."
                target/release/oxctl --sign "$img"
            done
        else
            echo "release.sh: skipping sign step — target/release/oxctl not built" >&2
            echo "  (run: cargo build --release -p oxwrtctl-cli)" >&2
        fi
    else
        echo "release.sh: firmware images present but no signing key env set — skipping signatures" >&2
        echo "  (see RELEASING.md → 'One-time setup: release-signing keypair')" >&2
    fi
    # Summary so the operator sees exactly what to upload.
    echo ""
    echo "---- firmware artifacts ----"
    echo "$IMAGES" | while IFS= read -r img; do
        [ -f "$img" ] || continue
        ls -lh "$img" "$img.sig" 2>/dev/null || ls -lh "$img"
    done
fi

# ── finale: paste-ready release body ──
echo ""
echo "==== $TAG tagged locally ===="
echo "next: git push origin main $TAG"
echo ""
echo "---- paste this as the GitHub release body ----"
echo ""
echo "$SECTION"
echo ""
echo "---- end ----"
