#!/bin/sh
# verity-wrap.sh — wrap a squashfs image with dm-verity.
#
# Produces:
#   1. A combined image: squashfs data + verity hash tree (appended)
#   2. A kernel cmdline fragment for dm-mod.create
#
# The combined image is a single file that serves as both the data device
# and the hash device (at different offsets). This is the standard layout
# used by Android and ChromeOS — the kernel reads data blocks from the
# start and hash blocks from the offset.
#
# Usage:
#   ./scripts/verity-wrap.sh <squashfs-image> <output-image> <cmdline-file>
#
# Example:
#   ./scripts/verity-wrap.sh build/rootfs.squashfs build/rootfs.verity build/verity-cmdline.txt
#
# Prerequisites:
#   - veritysetup (from cryptsetup package)
#   - Standard coreutils (stat, awk, cat)
#
# The kernel cmdline fragment goes into either:
#   - U-Boot bootargs (setenv bootargs "... $(cat verity-cmdline.txt)")
#   - DTS chosen { bootargs = "..."; }
#   - Or the OpenWRT image build's kernel cmdline injection point

set -eu

if [ $# -ne 3 ]; then
    echo "Usage: $0 <squashfs-image> <output-image> <cmdline-file>" >&2
    exit 1
fi

SQFS_IMAGE="$1"
OUTPUT_IMAGE="$2"
CMDLINE_FILE="$3"

if [ ! -f "$SQFS_IMAGE" ]; then
    echo "Error: squashfs image not found: $SQFS_IMAGE" >&2
    exit 1
fi

if ! command -v veritysetup >/dev/null 2>&1; then
    echo "Error: veritysetup not found. Install cryptsetup." >&2
    exit 1
fi

# Step 1: Get squashfs image size (in bytes and 4K blocks).
SQFS_BYTES=$(stat -c %s "$SQFS_IMAGE" 2>/dev/null || stat -f %z "$SQFS_IMAGE")
BLOCK_SIZE=4096

# Pad squashfs to a block boundary (veritysetup requires block-aligned data).
SQFS_BLOCKS=$(( (SQFS_BYTES + BLOCK_SIZE - 1) / BLOCK_SIZE ))
PADDED_BYTES=$(( SQFS_BLOCKS * BLOCK_SIZE ))
HASH_OFFSET_BLOCKS=$SQFS_BLOCKS

echo "squashfs: ${SQFS_BYTES} bytes, ${SQFS_BLOCKS} blocks (${BLOCK_SIZE}B)"

# Step 2: Create a padded copy of the squashfs image.
cp "$SQFS_IMAGE" "$OUTPUT_IMAGE"
if [ "$PADDED_BYTES" -gt "$SQFS_BYTES" ]; then
    PAD=$(( PADDED_BYTES - SQFS_BYTES ))
    dd if=/dev/zero bs=1 count=$PAD >> "$OUTPUT_IMAGE" 2>/dev/null
    echo "padded: +${PAD} bytes to block boundary"
fi

# Step 3: Run veritysetup format on the padded image. The hash tree is
# appended to the same file (--hash-offset = end of data). veritysetup
# writes the hash tree starting at that offset.
VERITY_OUTPUT=$(veritysetup format \
    "$OUTPUT_IMAGE" "$OUTPUT_IMAGE" \
    --data-block-size "$BLOCK_SIZE" \
    --hash-block-size "$BLOCK_SIZE" \
    --hash-offset "$PADDED_BYTES" \
    --salt - 2>&1)

echo "$VERITY_OUTPUT"

# Step 4: Extract the root hash and salt from veritysetup output.
ROOT_HASH=$(echo "$VERITY_OUTPUT" | grep "Root hash:" | awk '{print $NF}')
SALT=$(echo "$VERITY_OUTPUT" | grep "Salt:" | awk '{print $NF}')
UUID=$(echo "$VERITY_OUTPUT" | grep "UUID:" | awk '{print $NF}')

if [ -z "$ROOT_HASH" ]; then
    echo "Error: failed to extract root hash from veritysetup output" >&2
    exit 1
fi

# Step 5: Compute sectors for the dm-mod.create table.
# dm uses 512-byte sectors.
DATA_SECTORS=$(( SQFS_BLOCKS * (BLOCK_SIZE / 512) ))
HASH_OFFSET_SECTORS=$(( HASH_OFFSET_BLOCKS * (BLOCK_SIZE / 512) ))

# Step 6: Generate the kernel cmdline fragment.
#
# dm-mod.create syntax (Linux >= 5.1):
#   dm-mod.create="<name>,<uuid>,<minor>,ro,
#     0 <data_sectors> verity <version>
#     <data_dev> <hash_dev> <data_block_size> <hash_block_size>
#     <num_data_blocks> <hash_start_block> <algorithm> <root_hash> <salt>"
#
# Since data and hash are in the same image, both <data_dev> and
# <hash_dev> are the same device. On the target, this is typically
# /dev/ubiblock0_0 (NAND) or /dev/mmcblk0p2 (eMMC). We use a
# placeholder that the image build replaces.
#
# The `root=` parameter tells the kernel to mount the dm device as rootfs.

VERITY_TABLE="0 ${DATA_SECTORS} verity 1 ROOTDEV ROOTDEV ${BLOCK_SIZE} ${BLOCK_SIZE} ${SQFS_BLOCKS} ${HASH_OFFSET_BLOCKS} sha256 ${ROOT_HASH} ${SALT}"

cat > "$CMDLINE_FILE" << EOF
# dm-verity kernel cmdline fragment.
# Generated by verity-wrap.sh from: $SQFS_IMAGE
# Root hash: $ROOT_HASH
# Salt: $SALT
# UUID: $UUID
# Data blocks: $SQFS_BLOCKS (${BLOCK_SIZE}B each)
# Hash offset: block $HASH_OFFSET_BLOCKS
#
# Replace ROOTDEV with the actual block device path on the target:
#   /dev/ubiblock0_0  — NAND/UBI
#   /dev/mmcblk0p2    — eMMC
#   /dev/loop0        — testing with loop devices
#
# Add these to kernel bootargs (U-Boot or DTS):

root=/dev/dm-0 rootfstype=squashfs ro
dm-mod.create="verity-rootfs,,4,ro,${VERITY_TABLE}"
EOF

# Step 6b: Write a machine-readable root hash file (no comments, just the hash).
echo "$ROOT_HASH" > "${CMDLINE_FILE%.txt}.root-hash"

# Step 7: Summary.
OUTPUT_BYTES=$(stat -c %s "$OUTPUT_IMAGE" 2>/dev/null || stat -f %z "$OUTPUT_IMAGE")
OVERHEAD=$(( OUTPUT_BYTES - SQFS_BYTES ))
echo ""
echo "=== dm-verity wrap complete ==="
echo "  output:     $OUTPUT_IMAGE (${OUTPUT_BYTES} bytes)"
echo "  overhead:   ${OVERHEAD} bytes (hash tree + padding)"
echo "  root hash:  $ROOT_HASH"
echo "  cmdline:    $CMDLINE_FILE"
echo ""
echo "To test with a loop device:"
echo "  losetup /dev/loop0 $OUTPUT_IMAGE"
echo "  veritysetup open /dev/loop0 verity-test /dev/loop0 $ROOT_HASH --hash-offset=$PADDED_BYTES"
echo "  mount /dev/mapper/verity-test /mnt -t squashfs -o ro"
