//! Wifi config generator: translates `[[radios]]` + `[[wifi]]` entries
//! from the TOML config into per-phy hostapd.conf files that the
//! hostapd-5g / hostapd-2g services consume via bind-mount.
//!
//! Why runtime-generated rather than baked into the image: wifi config
//! (SSID, passphrase, channel, enabled/disabled) is the highest-turnover
//! user-facing setting on a router. Gating it on a reflash would make
//! the operator experience miserable. Instead:
//!
//!   - User edits via CRUD RPC (`wifi add`, `wifi update`, etc.) or
//!     `config-push` with a new TOML.
//!   - `reload` (or boot) calls `write_all()` which regenerates every
//!     per-phy hostapd.conf at /etc/oxwrt/hostapd/ (overlayfs — writable).
//!   - The hostapd-5g / hostapd-2g services bind-mount these files and
//!     get restarted by the supervisor, picking up the new config.
//!
//! On first boot after a clean flash, the overlay has no /etc/oxwrt/
//! hostapd/ yet; `write_all()` creates the dir + populates it before
//! the supervisor tries to start the hostapd services.

use crate::config::{Config, Radio, Wifi, WifiSecurity};
use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::io;
use std::path::{Path, PathBuf};

/// Directory where generated hostapd configs live. On overlayfs, matches
/// the bind-mount source in [[services.binds]] for hostapd-5g / -2g.
pub const CONF_DIR: &str = "/etc/oxwrt/hostapd";

/// Generate the hostapd.conf content for every radio that has at least
/// one non-hidden, non-disabled SSID. Returns a map of `phy → config
/// text`. Radios with no wifi entries are omitted (caller should not
/// write a file for them).
///
/// The first `[[wifi]]` entry for a radio becomes the primary BSS
/// (single-BSS for now; multi-SSID via `bss=` subsections is future
/// work). If a radio is marked `disabled = true` in config, no file is
/// emitted for it.
pub fn generate_all(cfg: &Config) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    // Index [[wifi]] by radio (phy name).
    let mut wifi_by_phy: BTreeMap<&str, Vec<&Wifi>> = BTreeMap::new();
    for w in &cfg.wifi {
        wifi_by_phy.entry(w.radio.as_str()).or_default().push(w);
    }
    for radio in &cfg.radios {
        if radio.disabled {
            continue;
        }
        let Some(wifis) = wifi_by_phy.get(radio.phy.as_str()) else {
            continue;
        };
        if wifis.is_empty() {
            continue;
        }
        // First wifi is the primary BSS; additional ones are ignored for
        // the moment (would need `bss=phyN-ap1` sub-sections; real multi-
        // SSID support is future work).
        let primary = wifis[0];
        let conf = build_hostapd_conf(radio, primary);
        out.insert(radio.phy.clone(), conf);
    }
    out
}

/// Write generated configs to `CONF_DIR`, creating the dir if needed.
/// Overwrites existing files atomically (write-to-.tmp + rename).
/// Stale files for phys that no longer have config get removed so a
/// subsequent hostapd start for that phy fails fast rather than running
/// with out-of-date credentials.
pub fn write_all(cfg: &Config) -> io::Result<()> {
    std::fs::create_dir_all(CONF_DIR)?;
    let configs = generate_all(cfg);
    let dir = Path::new(CONF_DIR);

    // First, remove any stale hostapd-*.conf not in the new set.
    let desired: std::collections::BTreeSet<PathBuf> = configs
        .keys()
        .map(|phy| dir.join(format!("{phy}.conf")))
        .collect();
    if let Ok(rd) = std::fs::read_dir(dir) {
        for ent in rd.flatten() {
            let p = ent.path();
            if p.extension().and_then(|s| s.to_str()) == Some("conf")
                && !desired.contains(&p)
            {
                let _ = std::fs::remove_file(&p);
                tracing::info!(path = %p.display(), "wifi: removed stale hostapd config");
            }
        }
    }

    // Then write/overwrite current ones.
    for (phy, conf) in &configs {
        let final_path = dir.join(format!("{phy}.conf"));
        let tmp_path = dir.join(format!("{phy}.conf.tmp"));
        std::fs::write(&tmp_path, conf.as_bytes())?;
        std::fs::rename(&tmp_path, &final_path)?;
        tracing::info!(phy, path = %final_path.display(), bytes = conf.len(),
            "wifi: wrote hostapd config");
    }
    Ok(())
}

/// Build one hostapd.conf from a radio + primary SSID.
fn build_hostapd_conf(radio: &Radio, w: &Wifi) -> String {
    let mut s = String::with_capacity(1024);
    writeln!(s, "# Auto-generated by oxwrtctl wifi::generate_all; do not edit.").unwrap();
    writeln!(s, "# Source: [[radios]] phy={} + [[wifi]] ssid={}", radio.phy, w.ssid).unwrap();
    writeln!(s).unwrap();
    writeln!(s, "interface={}-ap0", radio.phy).unwrap();
    writeln!(s, "bridge=br-lan").unwrap();
    writeln!(s, "driver=nl80211").unwrap();
    writeln!(s, "ctrl_interface=/tmp/hostapd").unwrap();
    writeln!(s, "ctrl_interface_group=0").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "ssid={}", w.ssid).unwrap();
    writeln!(s, "country_code=US").unwrap();
    if w.hidden {
        writeln!(s, "ignore_broadcast_ssid=1").unwrap();
    } else {
        writeln!(s, "ignore_broadcast_ssid=0").unwrap();
    }
    writeln!(s, "ieee80211d=1").unwrap();
    writeln!(s, "ieee80211h=1").unwrap();
    writeln!(s).unwrap();

    // Band-specific PHY settings.
    match radio.band.as_str() {
        "2g" => {
            writeln!(s, "hw_mode=g").unwrap();
            writeln!(s, "channel={}", radio.channel).unwrap();
            writeln!(s, "ieee80211n=1").unwrap();
            writeln!(s, "ieee80211ax=1").unwrap();
            writeln!(
                s,
                "ht_capab=[HT40+][SHORT-GI-20][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935]"
            )
            .unwrap();
        }
        "5g" | _ => {
            // Default 5 GHz with VHT80 if channel is a known 80 MHz-
            // anchor (36, 52, 100, 116, 132, 149). center_freq_seg0_idx
            // is channel + 6 for the lowest of the 4-channel group.
            writeln!(s, "hw_mode=a").unwrap();
            writeln!(s, "channel={}", radio.channel).unwrap();
            writeln!(s, "ieee80211n=1").unwrap();
            writeln!(s, "ieee80211ac=1").unwrap();
            writeln!(s, "ieee80211ax=1").unwrap();
            writeln!(
                s,
                "ht_capab=[HT40+][SHORT-GI-40][TX-STBC][RX-STBC1][MAX-AMSDU-7935][DSSS_CCK-40]"
            )
            .unwrap();
            let seg0 = vht_seg0(radio.channel);
            writeln!(s, "vht_oper_chwidth=1").unwrap();
            writeln!(s, "vht_oper_centr_freq_seg0_idx={seg0}").unwrap();
            writeln!(
                s,
                "vht_capab=[SHORT-GI-80][TX-STBC-2BY1][RX-STBC-1][RX-ANTENNA-PATTERN][TX-ANTENNA-PATTERN]"
            )
            .unwrap();
            writeln!(s, "he_oper_chwidth=1").unwrap();
            writeln!(s, "he_oper_centr_freq_seg0_idx={seg0}").unwrap();
        }
    }
    writeln!(s).unwrap();

    // Security.
    match w.security {
        WifiSecurity::Open => {
            writeln!(s, "wpa=0").unwrap();
            writeln!(s, "auth_algs=1").unwrap();
        }
        WifiSecurity::Wpa2 => {
            writeln!(s, "wpa=2").unwrap();
            writeln!(s, "wpa_passphrase={}", w.passphrase).unwrap();
            writeln!(s, "wpa_key_mgmt=WPA-PSK").unwrap();
            writeln!(s, "rsn_pairwise=CCMP").unwrap();
            writeln!(s, "ieee80211w=1").unwrap();
            writeln!(s, "auth_algs=1").unwrap();
        }
        WifiSecurity::Wpa3Sae => {
            writeln!(s, "wpa=2").unwrap();
            writeln!(s, "wpa_passphrase={}", w.passphrase).unwrap();
            writeln!(s, "wpa_key_mgmt=SAE").unwrap();
            writeln!(s, "rsn_pairwise=CCMP").unwrap();
            writeln!(s, "ieee80211w=2").unwrap(); // PMF required for SAE
            writeln!(s, "sae_require_mfp=1").unwrap();
            writeln!(s, "auth_algs=1").unwrap();
        }
        WifiSecurity::Wpa2Wpa3 => {
            writeln!(s, "wpa=2").unwrap();
            writeln!(s, "wpa_passphrase={}", w.passphrase).unwrap();
            writeln!(s, "wpa_key_mgmt=WPA-PSK SAE").unwrap();
            writeln!(s, "rsn_pairwise=CCMP").unwrap();
            writeln!(s, "ieee80211w=1").unwrap();
            writeln!(s, "auth_algs=1").unwrap();
        }
    }
    writeln!(s, "macaddr_acl=0").unwrap();
    writeln!(s, "ap_isolate=0").unwrap();
    s
}

/// Map a primary 5 GHz channel (20 MHz anchor) to its VHT80
/// center_freq_seg0 channel index (the center of the 4-channel 80 MHz
/// group). For channels that aren't the lowest of an 80 MHz group we
/// still return a sensible value (the canonical anchor). If the
/// operator picked a channel we don't recognise, fall back to the
/// channel itself so hostapd gets *something* and logs its own error
/// rather than us silently defaulting.
fn vht_seg0(channel: u16) -> u16 {
    match channel {
        36 | 40 | 44 | 48 => 42,
        52 | 56 | 60 | 64 => 58,
        100 | 104 | 108 | 112 => 106,
        116 | 120 | 124 | 128 => 122,
        132 | 136 | 140 | 144 => 138,
        149 | 153 | 157 | 161 => 155,
        165 | 169 | 173 | 177 => 171,
        _ => channel,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::{Radio, Wifi, WifiSecurity};

    fn mk_radio(phy: &str, band: &str, channel: u16, disabled: bool) -> Radio {
        Radio {
            phy: phy.into(),
            band: band.into(),
            channel,
            disabled,
        }
    }
    fn mk_wifi(radio: &str, ssid: &str, sec: WifiSecurity) -> Wifi {
        Wifi {
            radio: radio.into(),
            ssid: ssid.into(),
            security: sec,
            passphrase: "pass1234".into(),
            network: "lan".into(),
            hidden: false,
        }
    }

    #[test]
    fn conf_2g_wpa2_has_hw_mode_g() {
        let r = mk_radio("phy0", "2g", 6, false);
        let w = mk_wifi("phy0", "test2g", WifiSecurity::Wpa2);
        let c = build_hostapd_conf(&r, &w);
        assert!(c.contains("hw_mode=g"));
        assert!(c.contains("channel=6"));
        assert!(c.contains("ssid=test2g"));
        assert!(c.contains("wpa_key_mgmt=WPA-PSK"));
        assert!(c.contains("interface=phy0-ap0"));
        assert!(c.contains("bridge=br-lan"));
    }

    #[test]
    fn conf_5g_wpa3_has_sae_and_vht() {
        let r = mk_radio("phy1", "5g", 36, false);
        let w = mk_wifi("phy1", "test5g", WifiSecurity::Wpa3Sae);
        let c = build_hostapd_conf(&r, &w);
        assert!(c.contains("hw_mode=a"));
        assert!(c.contains("channel=36"));
        assert!(c.contains("wpa_key_mgmt=SAE"));
        assert!(c.contains("ieee80211w=2"));
        assert!(c.contains("vht_oper_centr_freq_seg0_idx=42"));
    }

    #[test]
    fn conf_open_has_no_passphrase() {
        let r = mk_radio("phy0", "2g", 6, false);
        let w = mk_wifi("phy0", "open", WifiSecurity::Open);
        let c = build_hostapd_conf(&r, &w);
        assert!(c.contains("wpa=0"));
        assert!(!c.contains("wpa_passphrase"));
    }

    #[test]
    fn vht_seg0_known_anchors() {
        assert_eq!(vht_seg0(36), 42);
        assert_eq!(vht_seg0(44), 42);
        assert_eq!(vht_seg0(149), 155);
        assert_eq!(vht_seg0(165), 171);
        assert_eq!(vht_seg0(999), 999);
    }
}
