//! coredhcp.yml renderer — writes `/etc/oxwrt/coredhcp.yml` from
//! `[dhcp]` in oxwrt.toml at boot + reload.
//!
//! Brings coredhcp under the same "oxwrt.toml is the source of
//! truth" umbrella that hickory-dns joined in the previous commit.
//! The service binds the generated file at `/etc/coredhcp.yml`; a
//! second bind-mount for the leases database (`leases.txt`) is
//! still operator-declared in `[[services.binds]]` because lease
//! state is runtime data, not config (see the earlier audit).
//!
//! Unset `[dhcp]` → no render; legacy bind-mounts at
//! `/usr/lib/oxwrt/services/dhcp/coredhcp.yml` keep working.

use std::fmt::Write as _;
use std::net::Ipv4Addr;
use std::path::Path;

use oxwrt_api::config::{Config, DhcpConfig, Network};

use crate::net::Error;

const OUT_PATH: &str = "/etc/oxwrt/coredhcp.yml";

/// Path the rendered server hands to the `range` plugin. Must match
/// the target of the leases-bind-mount in oxwrt.toml; that one is
/// operator-declared because lease state lives there.
const LEASE_FILE_IN_CONTAINER: &str = "/var/lib/coredhcp/leases.txt";

pub fn write_config(cfg: &Config) -> Result<(), Error> {
    let Some(dhcp) = cfg.dhcp.as_ref() else {
        return Ok(());
    };
    let text = render(cfg, dhcp)?;
    if let Some(parent) = Path::new(OUT_PATH).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Firewall(format!("coredhcp: mkdir {parent:?}: {e}")))?;
    }
    std::fs::write(OUT_PATH, text)
        .map_err(|e| Error::Firewall(format!("coredhcp: write {OUT_PATH}: {e}")))?;
    Ok(())
}

/// Pure text generator. coredhcp's plugin args are positional one-
/// liners: one arg string per plugin. See the shipped example file
/// for the gotcha — `lease_time: 3600` is interpreted as the arg
/// literal "3600" which Go's time.ParseDuration rejects. Always
/// emit durations in Go's form ("12h" etc.).
pub fn render(cfg: &Config, dhcp: &DhcpConfig) -> Result<String, Error> {
    // Resolve the target network.
    let net = cfg.networks.iter().find(|n| n.name() == dhcp.network).ok_or_else(|| {
        Error::Firewall(format!(
            "coredhcp: [dhcp].network = {:?} doesn't match any [[networks]] entry",
            dhcp.network
        ))
    })?;
    let (iface, router_addr, prefix) = match net {
        Network::Lan {
            bridge,
            address,
            prefix,
            ..
        } => (bridge.as_str(), *address, *prefix),
        Network::Simple {
            iface,
            address,
            prefix,
            ..
        } => (iface.as_str(), *address, *prefix),
        Network::Wan { .. } => {
            return Err(Error::Firewall(format!(
                "coredhcp: [dhcp].network = {:?} is a WAN; DHCPv4 server must bind to LAN/Simple",
                dhcp.network
            )));
        }
    };

    let netmask = prefix_to_netmask_v4(prefix);
    let server_id = router_addr;
    let gateway = dhcp.gateway.unwrap_or(router_addr);
    let dns_servers = if dhcp.dns_servers.is_empty() {
        vec![router_addr]
    } else {
        dhcp.dns_servers.clone()
    };

    // Pool bounds: operator-supplied or defaulted to .100–.250 of
    // the network. Conservative — leaves .2-.99 for static
    // assignments and .251-.254 as a reserve.
    let (pool_start, pool_end) = derive_pool(router_addr, prefix, dhcp)?;

    let mut s = String::new();
    writeln!(s, "# Auto-generated by oxwrtd coredhcp::write_config.").unwrap();
    writeln!(s, "# Source of truth: /etc/oxwrt/oxwrt.toml [dhcp] section.").unwrap();
    writeln!(s, "# Edit oxwrt.toml + `oxctl reload`, not this file.").unwrap();
    writeln!(s).unwrap();
    writeln!(s, "server4:").unwrap();
    writeln!(s, "  listen:").unwrap();
    // coredhcp's listen syntax: "%<iface>" binds via SO_BINDTODEVICE.
    writeln!(s, "    - \"%{iface}\"").unwrap();
    writeln!(s, "  plugins:").unwrap();
    writeln!(s, "    - lease_time: {}", dhcp.lease_time).unwrap();
    writeln!(s, "    - server_id: {server_id}").unwrap();
    let dns_list = dns_servers
        .iter()
        .map(|ip| ip.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    writeln!(s, "    - dns: {dns_list}").unwrap();
    writeln!(s, "    - router: {gateway}").unwrap();
    writeln!(s, "    - netmask: {netmask}").unwrap();
    // range plugin: "<leasefile> <start> <end> <lease_time>"
    writeln!(
        s,
        "    - range: {LEASE_FILE_IN_CONTAINER} {pool_start} {pool_end} {}",
        dhcp.lease_time
    )
    .unwrap();
    Ok(s)
}

fn derive_pool(
    router: Ipv4Addr,
    prefix: u8,
    dhcp: &DhcpConfig,
) -> Result<(Ipv4Addr, Ipv4Addr), Error> {
    // Explicit override path: trust the operator's bounds.
    if let (Some(s), Some(e)) = (dhcp.pool_start, dhcp.pool_end) {
        if u32::from(s) > u32::from(e) {
            return Err(Error::Firewall(format!(
                "coredhcp: pool_start {s} > pool_end {e}"
            )));
        }
        return Ok((s, e));
    }
    if dhcp.pool_start.is_some() != dhcp.pool_end.is_some() {
        return Err(Error::Firewall(
            "coredhcp: pool_start and pool_end must both be set or both omitted"
                .into(),
        ));
    }
    // Auto-derive: compute network base from router addr + prefix,
    // then .100 / .250 offsets within it. Clamp so we stay inside
    // the usable range for the prefix.
    let prefix = prefix.min(32);
    let host_bits = 32 - u32::from(prefix);
    if host_bits < 2 {
        // /31 and /32 don't leave room for a pool; operator must
        // supply explicit bounds.
        return Err(Error::Firewall(format!(
            "coredhcp: auto-derived pool needs /30 or larger (got /{prefix}); \
             set pool_start + pool_end explicitly"
        )));
    }
    let mask = if host_bits == 32 {
        0
    } else {
        !((1u32 << host_bits) - 1)
    };
    let network_base = u32::from(router) & mask;
    let usable_first = network_base + 1; // .0 is network addr on most masks
    let broadcast = if host_bits == 32 {
        u32::MAX
    } else {
        network_base | !mask
    };
    let usable_last = broadcast - 1;
    let desired_start = (network_base + 100).max(usable_first).min(usable_last);
    let desired_end = (network_base + 250).max(desired_start).min(usable_last);
    Ok((Ipv4Addr::from(desired_start), Ipv4Addr::from(desired_end)))
}

fn prefix_to_netmask_v4(prefix: u8) -> Ipv4Addr {
    if prefix >= 32 {
        return Ipv4Addr::new(255, 255, 255, 255);
    }
    let mask = !((1u32 << (32 - u32::from(prefix))) - 1);
    Ipv4Addr::from(mask)
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxwrt_api::config::{Config, Control, DhcpConfig, Firewall, Network};
    use std::path::PathBuf;

    fn cfg_lan_only(prefix: u8) -> Config {
        Config {
            hostname: "t".into(),
            timezone: None,
            networks: vec![Network::Lan {
                name: "lan".into(),
                bridge: "br-lan".into(),
                members: vec![],
                vlan_filtering: false,
                vlan_ports: vec![],
                address: Ipv4Addr::new(192, 168, 50, 1),
                prefix,
                ipv6_address: None,
                ipv6_prefix: None,
                ipv6_subnet_id: None,
                router_advertisements: None,
            }],
            firewall: Firewall::default(),
            radios: vec![],
            wifi: vec![],
            services: vec![],
            port_forwards: vec![],
            wireguard: vec![],
            ddns: vec![],
            metrics: None,
            routes: vec![],
            routes6: vec![],
            blocklists: vec![],
            upnp: None,
            vpn_client: vec![],
            backup_sftp: None,
            dns: None,
            dhcp: None,
            ntp: None,
            control: Control {
                listen: vec![],
                authorized_keys: PathBuf::from("/x"),
                clients: vec![],
            },
        }
    }

    fn default_dhcp() -> DhcpConfig {
        DhcpConfig {
            network: "lan".into(),
            lease_time: "12h".into(),
            pool_start: None,
            pool_end: None,
            dns_servers: vec![],
            gateway: None,
        }
    }

    #[test]
    fn netmask_24() {
        assert_eq!(prefix_to_netmask_v4(24), Ipv4Addr::new(255, 255, 255, 0));
        assert_eq!(prefix_to_netmask_v4(16), Ipv4Addr::new(255, 255, 0, 0));
        assert_eq!(prefix_to_netmask_v4(30), Ipv4Addr::new(255, 255, 255, 252));
    }

    #[test]
    fn render_24_defaults() {
        let cfg = cfg_lan_only(24);
        let out = render(&cfg, &default_dhcp()).unwrap();
        assert!(out.contains("listen:\n    - \"%br-lan\""));
        assert!(out.contains("lease_time: 12h"));
        assert!(out.contains("server_id: 192.168.50.1"));
        assert!(out.contains("dns: 192.168.50.1"));
        assert!(out.contains("router: 192.168.50.1"));
        assert!(out.contains("netmask: 255.255.255.0"));
        assert!(out.contains("range: /var/lib/coredhcp/leases.txt 192.168.50.100 192.168.50.250 12h"));
    }

    #[test]
    fn operator_pool_override_respected() {
        let cfg = cfg_lan_only(24);
        let mut dhcp = default_dhcp();
        dhcp.pool_start = Some(Ipv4Addr::new(192, 168, 50, 50));
        dhcp.pool_end = Some(Ipv4Addr::new(192, 168, 50, 99));
        let out = render(&cfg, &dhcp).unwrap();
        assert!(out.contains("192.168.50.50 192.168.50.99"));
    }

    #[test]
    fn half_pool_is_error() {
        let cfg = cfg_lan_only(24);
        let mut dhcp = default_dhcp();
        dhcp.pool_start = Some(Ipv4Addr::new(192, 168, 50, 50));
        assert!(render(&cfg, &dhcp).is_err());
    }

    #[test]
    fn inverted_pool_is_error() {
        let cfg = cfg_lan_only(24);
        let mut dhcp = default_dhcp();
        dhcp.pool_start = Some(Ipv4Addr::new(192, 168, 50, 99));
        dhcp.pool_end = Some(Ipv4Addr::new(192, 168, 50, 50));
        assert!(render(&cfg, &dhcp).is_err());
    }

    #[test]
    fn explicit_dns_servers_override() {
        let cfg = cfg_lan_only(24);
        let mut dhcp = default_dhcp();
        dhcp.dns_servers = vec![Ipv4Addr::new(1, 1, 1, 1), Ipv4Addr::new(9, 9, 9, 9)];
        let out = render(&cfg, &dhcp).unwrap();
        assert!(out.contains("dns: 1.1.1.1 9.9.9.9"));
    }

    #[test]
    fn unknown_network_is_error() {
        let cfg = cfg_lan_only(24);
        let mut dhcp = default_dhcp();
        dhcp.network = "nonexistent".into();
        assert!(render(&cfg, &dhcp).is_err());
    }

    #[test]
    fn wan_target_is_error() {
        let mut cfg = cfg_lan_only(24);
        cfg.networks.push(Network::Wan {
            name: "wan".into(),
            iface: "eth1".into(),
            wan: oxwrt_api::config::WanConfig::Dhcp,
            ipv6_pd: false,
            sqm: None,
            priority: 100,
            probe_target: None,
        });
        let mut dhcp = default_dhcp();
        dhcp.network = "wan".into();
        let err = render(&cfg, &dhcp).unwrap_err();
        assert!(format!("{err:?}").contains("DHCPv4 server must bind"));
    }

    #[test]
    fn small_prefix_requires_explicit_pool() {
        // /31 is valid in some niche P2P cases but doesn't leave
        // room for auto-derived 100-250.
        let cfg = cfg_lan_only(31);
        let err = render(&cfg, &default_dhcp()).unwrap_err();
        assert!(format!("{err:?}").contains("auto-derived pool"));
    }
}
