//! corerad.toml generator — writes the `[[interfaces]]` config the
//! corerad service container reads, derived from each `[[networks]]`
//! entry that declares an IPv6 address.
//!
//! Why generate instead of shipping a static file: the corerad config
//! must name the exact iface to advertise on (`br-lan`), the prefix
//! to advertise (`fd::/64`), and the managed/other-config flags. All
//! three change when the operator adds an IPv6 prefix or another LAN
//! — regenerating keeps corerad in sync with `[[networks]]` without a
//! rebuild.
//!
//! Static vs dynamic path: the image ships `/usr/lib/oxwrt/services/
//! corerad/corerad.toml` as a ULA-only fallback; the service binds
//! that file at `/etc/corerad.toml`. When this generator runs, it
//! writes to `/etc/oxwrt/corerad.toml` and the service bind-mount
//! target (declared in oxwrt.toml) points there — so operator's
//! cfg.toml is the source of truth post-boot, the shipped file is
//! just the bootstrap default.

use std::fmt::Write as _;
use std::path::Path;

use oxwrt_api::config::{Config, Network};

use crate::net::Error;

const OUT_PATH: &str = "/etc/oxwrt/corerad.toml";

/// Render + write `/etc/oxwrt/corerad.toml` based on every network
/// with an `ipv6_address`. Zero v6 prefixes → empty file (corerad
/// starts, advertises nothing — safe no-op). Called on boot and
/// on reload.
pub fn write_config(cfg: &Config) -> Result<(), Error> {
    let text = render(cfg);
    if let Some(parent) = Path::new(OUT_PATH).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Firewall(format!("corerad: mkdir {parent:?}: {e}")))?;
    }
    std::fs::write(OUT_PATH, text)
        .map_err(|e| Error::Firewall(format!("corerad: write {OUT_PATH}: {e}")))?;
    Ok(())
}

/// Pure text generator — one `[[interfaces]]` block per v6-enabled
/// network. Kept separate from the fs-write path for unit testing.
pub fn render(cfg: &Config) -> String {
    let mut s = String::new();
    writeln!(s, "# Auto-generated by oxwrtd corerad::write_config.").unwrap();
    writeln!(
        s,
        "# Source of truth: /etc/oxwrt.toml [[networks]] ipv6_* fields."
    )
    .unwrap();
    writeln!(s, "# Edit oxwrt.toml + `oxctl reload`, not this file.").unwrap();
    writeln!(s).unwrap();
    for net in &cfg.networks {
        let Some((addr, prefix)) = net.ipv6() else {
            continue;
        };
        // The prefix to advertise is the network portion of `addr`.
        // Zero out the host bits so clients see e.g. `fd::/64` and
        // not `fd::1/64` (SLAAC is keyed on the network prefix, not
        // the router's host bits).
        let net_prefix = mask_prefix(addr, prefix);
        // advertise-on iface: bridge for Lan, iface for Simple.
        let iface = match net {
            Network::Lan { bridge, .. } => bridge.as_str(),
            Network::Simple { iface, .. } => iface.as_str(),
            Network::Wan { .. } => continue,
        };
        writeln!(s, "[[interfaces]]").unwrap();
        writeln!(s, "  names = [\"{iface}\"]").unwrap();
        writeln!(s, "  advertise = true").unwrap();
        writeln!(s, "  max_interval = \"180s\"").unwrap();
        writeln!(s, "  min_interval = \"auto\"").unwrap();
        writeln!(s, "  default_lifetime = \"1800s\"").unwrap();
        // M=0, O=0 — pure SLAAC. Flip later when/if DHCPv6 stateful
        // lands. Keep the field explicit so intent is obvious.
        writeln!(s, "  managed = false").unwrap();
        writeln!(s, "  other_config = false").unwrap();
        writeln!(s).unwrap();
        writeln!(s, "  [[interfaces.prefix]]").unwrap();
        writeln!(s, "    prefix = \"{net_prefix}/{prefix}\"").unwrap();
        writeln!(s, "    on_link = true").unwrap();
        writeln!(s, "    autonomous = true").unwrap();
        writeln!(s).unwrap();
    }
    s
}

/// Zero out the host bits below `prefix` on `addr`. For prefix=64
/// and addr=fd12:3456:789a:1::1, returns fd12:3456:789a:1::.
fn mask_prefix(addr: std::net::Ipv6Addr, prefix: u8) -> std::net::Ipv6Addr {
    if prefix >= 128 {
        return addr;
    }
    let octets = addr.octets();
    let mut bits = u128::from_be_bytes(octets);
    let shift = 128 - u32::from(prefix);
    bits &= !((1u128 << shift) - 1);
    std::net::Ipv6Addr::from(bits.to_be_bytes())
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxwrt_api::config::{Config, Control, Firewall, Network};
    use std::net::{Ipv4Addr, Ipv6Addr};
    use std::path::PathBuf;

    fn cfg_with_v6_lan() -> Config {
        Config {
            hostname: "t".into(),
            timezone: None,
            networks: vec![Network::Lan {
                name: "lan".into(),
                bridge: "br-lan".into(),
                members: vec![],
                vlan_filtering: false,
                vlan_ports: vec![],
                address: Ipv4Addr::new(192, 168, 50, 1),
                prefix: 24,
                ipv6_address: Some("fdbe:cafe::1".parse().unwrap()),
                ipv6_prefix: Some(64),
                ipv6_subnet_id: None,
            }],
            firewall: Firewall::default(),
            radios: vec![],
            wifi: vec![],
            services: vec![],
            port_forwards: vec![],
            wireguard: vec![],
            ddns: vec![],
            metrics: None,
            routes: vec![],
            routes6: vec![],
            blocklists: vec![],
            upnp: None,
            vpn_client: vec![],
            backup_sftp: None,
            dns: None,
            dhcp: None,
            control: Control {
                listen: vec!["[::1]:51820".into()],
                authorized_keys: PathBuf::from("/x"),
                clients: vec![],
            },
        }
    }

    #[test]
    fn render_emits_interfaces_block() {
        let cfg = cfg_with_v6_lan();
        let out = render(&cfg);
        assert!(out.contains("[[interfaces]]"));
        assert!(out.contains(r#"names = ["br-lan"]"#));
        assert!(out.contains(r#"prefix = "fdbe:cafe::/64""#), "got:\n{out}");
        assert!(out.contains("advertise = true"));
    }

    #[test]
    fn render_empty_when_no_v6() {
        let mut cfg = cfg_with_v6_lan();
        if let Network::Lan { ipv6_address, .. } = &mut cfg.networks[0] {
            *ipv6_address = None;
        }
        let out = render(&cfg);
        assert!(!out.contains("[[interfaces]]"));
    }

    #[test]
    fn mask_prefix_basic() {
        let addr: Ipv6Addr = "fdbe:cafe::1".parse().unwrap();
        let masked = mask_prefix(addr, 64);
        assert_eq!(masked, "fdbe:cafe::".parse::<Ipv6Addr>().unwrap());
        // /48 zeroes two more bytes
        let masked48 = mask_prefix("fdbe:cafe:1234::1".parse().unwrap(), 48);
        assert_eq!(masked48, "fdbe:cafe:1234::".parse::<Ipv6Addr>().unwrap());
    }

    #[test]
    fn mask_prefix_128_is_identity() {
        let addr: Ipv6Addr = "fdbe:cafe::1".parse().unwrap();
        assert_eq!(mask_prefix(addr, 128), addr);
    }
}
