//! hickory-dns config renderer — writes `/etc/oxwrt/named.toml`
//! from `[dns]` in oxwrt.toml at boot + reload.
//!
//! Closes one of the last four holdouts of the "everything lives in
//! oxwrt.toml" property: before this module existed, the hickory
//! service bound an image-shipped file at
//! `/usr/lib/oxwrt/services/dns/named.toml`, and switching DoH
//! upstreams meant editing that baked file. Now oxwrtd renders to
//! `/etc/oxwrt/named.toml` and the service's bind points there.
//!
//! Unset `[dns]` → no render; the image-shipped fallback still
//! loads. That preserves backward compat for existing installs
//! that haven't migrated their service binds.

use std::fmt::Write as _;
use std::path::Path;

use oxwrt_api::config::{Config, DnsConfig, DnsUpstream};

use crate::net::Error;

const OUT_PATH: &str = "/etc/oxwrt/named.toml";

/// Render + write `/etc/oxwrt/named.toml`. No-op if `cfg.dns` is
/// None (operator hasn't migrated yet — legacy bind-mount path
/// still works).
pub fn write_config(cfg: &Config) -> Result<(), Error> {
    let Some(dns) = cfg.dns.as_ref() else {
        return Ok(());
    };
    let text = render(dns);
    if let Some(parent) = Path::new(OUT_PATH).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Firewall(format!("hickory: mkdir {parent:?}: {e}")))?;
    }
    std::fs::write(OUT_PATH, text)
        .map_err(|e| Error::Firewall(format!("hickory: write {OUT_PATH}: {e}")))?;
    Ok(())
}

/// Pure text generator. Targets hickory-dns 0.26 — per the
/// upstream schema, the forward store is a nested
/// `[[zones.stores.name_servers.connections]]` so upstream choice
/// (protocol, port, server_name, path) lives under each upstream.
pub fn render(dns: &DnsConfig) -> String {
    let mut s = String::new();
    writeln!(s, "# Auto-generated by oxwrtd hickory::write_config.").unwrap();
    writeln!(
        s,
        "# Source of truth: /etc/oxwrt/oxwrt.toml [dns] section."
    )
    .unwrap();
    writeln!(s, "# Edit oxwrt.toml + `oxctl reload`, not this file.").unwrap();
    writeln!(s).unwrap();

    // Listen addresses + port.
    write!(s, "listen_addrs_ipv4 = [").unwrap();
    for (i, addr) in dns.listen_v4.iter().enumerate() {
        if i > 0 {
            write!(s, ", ").unwrap();
        }
        write!(s, "\"{addr}\"").unwrap();
    }
    writeln!(s, "]").unwrap();
    writeln!(s, "listen_port = {}", dns.listen_port).unwrap();
    // hickory wants a writable dir for its journal / rrset cache;
    // the dns service container gives it `/var`.
    writeln!(s, "directory = \"/var\"").unwrap();
    writeln!(s).unwrap();

    // Root forward zone — everything not locally authoritative
    // forwards to upstream.
    writeln!(s, "[[zones]]").unwrap();
    writeln!(s, "zone = \".\"").unwrap();
    writeln!(s, "zone_type = \"External\"").unwrap();
    writeln!(s).unwrap();

    if !dns.upstreams.is_empty() {
        writeln!(s, "[[zones.stores]]").unwrap();
        writeln!(s, "type = \"forward\"").unwrap();
        writeln!(s).unwrap();
        for up in &dns.upstreams {
            render_upstream(&mut s, up);
        }
    }
    s
}

fn render_upstream(s: &mut String, up: &DnsUpstream) {
    let port = up.port.unwrap_or_else(|| default_port_for(&up.protocol));
    let server_name = up.server_name.as_deref().unwrap_or("");
    let path = up.path.as_deref().unwrap_or("/dns-query");

    writeln!(s, "[[zones.stores.name_servers]]").unwrap();
    writeln!(s, "ip = \"{}\"", up.ip).unwrap();
    writeln!(
        s,
        "trust_negative_responses = {}",
        up.trust_negative_responses
    )
    .unwrap();
    writeln!(s).unwrap();
    writeln!(s, "[[zones.stores.name_servers.connections]]").unwrap();
    writeln!(s, "port = {port}").unwrap();
    match up.protocol.as_str() {
        "https" => writeln!(
            s,
            "protocol = {{ type = \"https\", server_name = \"{server_name}\", path = \"{path}\" }}"
        )
        .unwrap(),
        "quic" => writeln!(
            s,
            "protocol = {{ type = \"quic\", server_name = \"{server_name}\" }}"
        )
        .unwrap(),
        "tls" => writeln!(
            s,
            "protocol = {{ type = \"tls\", server_name = \"{server_name}\" }}"
        )
        .unwrap(),
        "udp" => writeln!(s, "protocol = {{ type = \"udp\" }}").unwrap(),
        "tcp" => writeln!(s, "protocol = {{ type = \"tcp\" }}").unwrap(),
        other => {
            // Unknown protocol — emit it verbatim so hickory rejects
            // with a clear error rather than silently defaulting to
            // something unexpected.
            writeln!(s, "protocol = {{ type = \"{other}\" }}").unwrap();
        }
    }
    writeln!(s).unwrap();
}

fn default_port_for(protocol: &str) -> u16 {
    match protocol {
        "https" => 443,
        "quic" | "tls" => 853,
        _ => 53,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::net::{IpAddr, Ipv4Addr};

    fn cfg_with(upstreams: Vec<DnsUpstream>) -> DnsConfig {
        DnsConfig {
            listen_v4: vec![Ipv4Addr::UNSPECIFIED],
            listen_port: 15353,
            upstreams,
        }
    }

    #[test]
    fn empty_upstreams_still_valid() {
        let text = render(&cfg_with(vec![]));
        assert!(text.contains("listen_port = 15353"));
        assert!(text.contains("[[zones]]"));
        assert!(!text.contains("name_servers"));
    }

    #[test]
    fn https_upstream_with_defaults() {
        let up = DnsUpstream {
            ip: IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1)),
            port: None,
            protocol: "https".into(),
            server_name: Some("cloudflare-dns.com".into()),
            path: None,
            trust_negative_responses: false,
        };
        let text = render(&cfg_with(vec![up]));
        assert!(text.contains("ip = \"1.1.1.1\""));
        assert!(text.contains("port = 443"));
        assert!(text.contains("server_name = \"cloudflare-dns.com\""));
        assert!(text.contains("/dns-query"));
    }

    #[test]
    fn quic_upstream_defaults_port_853() {
        let up = DnsUpstream {
            ip: IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1)),
            port: None,
            protocol: "quic".into(),
            server_name: Some("cloudflare-dns.com".into()),
            path: None,
            trust_negative_responses: false,
        };
        let text = render(&cfg_with(vec![up]));
        assert!(text.contains("port = 853"));
        assert!(text.contains("type = \"quic\""));
    }

    #[test]
    fn plaintext_upstream_emits_minimal_protocol_entry() {
        let up = DnsUpstream {
            ip: IpAddr::V4(Ipv4Addr::new(9, 9, 9, 9)),
            port: Some(53),
            protocol: "udp".into(),
            server_name: None,
            path: None,
            trust_negative_responses: true,
        };
        let text = render(&cfg_with(vec![up]));
        assert!(text.contains("port = 53"));
        assert!(text.contains("protocol = { type = \"udp\" }"));
        assert!(text.contains("trust_negative_responses = true"));
    }

    #[test]
    fn multiple_upstreams_all_emitted_in_order() {
        let a = DnsUpstream {
            ip: IpAddr::V4(Ipv4Addr::new(1, 1, 1, 1)),
            port: None,
            protocol: "https".into(),
            server_name: Some("cloudflare-dns.com".into()),
            path: None,
            trust_negative_responses: false,
        };
        let b = DnsUpstream {
            ip: IpAddr::V4(Ipv4Addr::new(9, 9, 9, 9)),
            port: None,
            protocol: "https".into(),
            server_name: Some("dns.quad9.net".into()),
            path: None,
            trust_negative_responses: false,
        };
        let text = render(&cfg_with(vec![a, b]));
        let cf_pos = text.find("cloudflare-dns.com").unwrap();
        let q9_pos = text.find("dns.quad9.net").unwrap();
        assert!(cf_pos < q9_pos, "upstreams must render in config order");
    }
}
