//! miniupnpd config renderer.
//!
//! We don't ship the miniupnpd binary in oxwrt today — cross-
//! building it for aarch64-musl requires a Makefile `services-upnpd`
//! target and is tracked as a separate follow-up. What *does* land
//! here is the bits we always end up owning regardless of who
//! builds the binary:
//!
//!   1. `Config::upnp` schema (see oxwrt-api).
//!   2. This module: renders `/etc/oxwrt/miniupnpd.conf` from the
//!      schema, idempotently on boot + reload.
//!   3. A commented `[[services]]` stanza in the example config so
//!      operators who provide their own binary can wire it up.
//!
//! Rendering happens even when the binary is absent — the file is
//! cheap and having it in place means the operator can drop a
//! binary into the rootfs + add the service entry + reload without
//! having to touch oxwrtd code.
//!
//! # Why a separate nftables table
//!
//! miniupnpd installs its own DNAT/filter rules to expose the
//! transient per-client mappings. Pointing it at its own
//! `oxwrt-upnpd` table means:
//! - our `install_firewall` never clobbers miniupnpd's live
//!   mappings,
//! - miniupnpd's reloads never clobber our rules,
//! - `nft list table ip oxwrt-upnpd` gives operators a one-line
//!   "what's currently mapped?" view.
//!
//! The oxwrt main table gets a `jump` rule from prerouting into
//! `oxwrt-upnpd` — that wiring is a TODO for when the binary
//! actually ships.

use std::fs;
use std::path::Path;

use oxwrt_api::config::{Config, UpnpConfig};

const CONFIG_PATH: &str = "/etc/oxwrt/miniupnpd.conf";
/// Persistent device UUID. miniupnpd advertises this in its
/// SSDP payload; clients pin it so the UUID must NOT regenerate
/// every reload (that would spam "device replaced" on every
/// connected console). We read it if present, generate + persist
/// on first install.
const UUID_PATH: &str = "/etc/oxwrt/miniupnpd.uuid";

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("io: {0}")]
    Io(#[from] std::io::Error),
}

/// Write `/etc/oxwrt/miniupnpd.conf` if `cfg.upnp` is Some. No-op
/// when disabled — we leave any prior config file in place rather
/// than deleting it, so re-enabling UPnP doesn't race with the
/// service's read of a freshly-absent file.
pub fn write_config(cfg: &Config) -> Result<(), Error> {
    let Some(upnp) = &cfg.upnp else {
        tracing::debug!("miniupnpd: disabled (no [upnp] in config)");
        return Ok(());
    };
    if let Some(parent) = Path::new(CONFIG_PATH).parent() {
        fs::create_dir_all(parent)?;
    }
    let uuid = load_or_create_uuid()?;
    let body = render(upnp, &uuid);
    fs::write(CONFIG_PATH, body)?;
    tracing::info!(path = CONFIG_PATH, "miniupnpd: config written");
    Ok(())
}

/// Read the persisted miniupnpd device UUID, or generate a new
/// one via /proc/sys/kernel/random/uuid and persist it. The file
/// lives under /etc/oxwrt/ (kept across sysupgrade via the
/// keeplist) so an operator flashing a new image keeps the same
/// UPnP-device identity — clients don't see a "new device" churn
/// every upgrade.
fn load_or_create_uuid() -> Result<String, Error> {
    if let Ok(existing) = fs::read_to_string(UUID_PATH) {
        let t = existing.trim();
        if !t.is_empty() {
            return Ok(t.to_string());
        }
    }
    // /proc/sys/kernel/random/uuid returns a fresh UUID v4 every
    // read. This is the same source miniupnpd's Alpine postinstall
    // uses, so format compatibility is automatic.
    let fresh = fs::read_to_string("/proc/sys/kernel/random/uuid")?;
    let fresh = fresh.trim().to_string();
    if let Some(parent) = Path::new(UUID_PATH).parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(UUID_PATH, &fresh)?;
    Ok(fresh)
}

/// Pure function for unit-testing. Matches the miniupnpd.conf
/// format documented at upstream man page miniupnpd(8). UUID is
/// caller-supplied so tests can pin a fixed value; prod callers
/// source it from load_or_create_uuid.
fn render(u: &UpnpConfig, uuid: &str) -> String {
    let natpmp = if u.enable_natpmp { "yes" } else { "no" };
    format!(
        "# Generated by oxwrtd — do not edit.\n\
         # Source: [upnp] in /etc/oxwrt.toml.\n\
         ext_ifname={wan}\n\
         listening_ip={lan}\n\
         enable_upnp=yes\n\
         enable_natpmp={natpmp}\n\
         # Transient mappings stay in dedicated upnpd-owned nftables\n\
         # objects (filter + nat chains in miniupnpd's own tables) so\n\
         # oxwrt's firewall reloads don't collide with miniupnpd's\n\
         # runtime rule churn. Option names match miniupnpd 2.3.x\n\
         # (verified against options.c):\n\
         #   upnp_table_name           — NAT table name (default 'filter')\n\
         #   upnp_nat_chain            — NAT input/redirect chain\n\
         #   upnp_nat_postrouting_chain — NAT postrouting chain\n\
         #   upnp_forward_chain        — FILTER forward chain\n\
         upnp_table_name=oxwrt-upnpd\n\
         upnp_nat_chain=prerouting_upnpd\n\
         upnp_nat_postrouting_chain=postrouting_upnpd\n\
         upnp_forward_chain=forward_upnpd\n\
         # Port range miniupnpd is allowed to map on the WAN side.\n\
         # Ports below min_port stay exclusive to [[port_forwards]]\n\
         # declared statically — prevents clients from grabbing\n\
         # well-known ports via UPnP.\n\
         allow {min_port}-{max_port} 0.0.0.0/0 {min_port}-{max_port}\n\
         deny 0-65535 0.0.0.0/0 0-65535\n\
         # Device UUID persisted at /etc/oxwrt/miniupnpd.uuid so\n\
         # it stays stable across reboots + sysupgrade.\n\
         uuid={uuid}\n",
        wan = u.wan,
        lan = u.lan,
        natpmp = natpmp,
        min_port = u.min_port,
        max_port = u.max_port,
        uuid = uuid,
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample() -> UpnpConfig {
        UpnpConfig {
            wan: "eth1".into(),
            lan: "br-lan".into(),
            min_port: 1024,
            max_port: 65535,
            enable_natpmp: true,
        }
    }

    #[test]
    fn render_includes_critical_directives() {
        let out = render(&sample(), "00000000-0000-0000-0000-000000000001");
        assert!(out.contains("ext_ifname=eth1"));
        assert!(out.contains("listening_ip=br-lan"));
        assert!(out.contains("enable_upnp=yes"));
        assert!(out.contains("enable_natpmp=yes"));
        assert!(out.contains("upnp_table_name=oxwrt-upnpd"));
        assert!(out.contains("allow 1024-65535"));
    }

    #[test]
    fn natpmp_disabled_renders_no() {
        let mut c = sample();
        c.enable_natpmp = false;
        assert!(render(&c, "00000000-0000-0000-0000-000000000001").contains("enable_natpmp=no"));
    }

    #[test]
    fn port_range_renders() {
        let mut c = sample();
        c.min_port = 8000;
        c.max_port = 9000;
        assert!(render(&c, "00000000-0000-0000-0000-000000000001").contains("allow 8000-9000"));
    }

    #[test]
    fn toml_defaults_apply() {
        let toml = r#"
wan = "eth1"
lan = "br-lan"
"#;
        let u: UpnpConfig = toml::from_str(toml).unwrap();
        assert_eq!(u.min_port, 1024);
        assert_eq!(u.max_port, 65535);
        assert!(u.enable_natpmp);
    }

    /// The generator header includes the "do not edit" marker so
    /// operators SSH-tailing the config file know regenerating it
    /// via oxwrtd reload wipes manual changes.
    #[test]
    fn render_header_warns_against_manual_edits() {
        let out = render(&sample(), "00000000-0000-0000-0000-000000000001");
        assert!(out.contains("do not edit"));
        assert!(out.contains("/etc/oxwrt.toml"));
    }

    /// Deny-all rule after the allow range. Order matters in
    /// miniupnpd.conf — a stray rule ordering flip would silently
    /// permit all ports regardless of min_port/max_port.
    #[test]
    fn render_deny_follows_allow() {
        let out = render(&sample(), "00000000-0000-0000-0000-000000000001");
        let allow_pos = out.find("allow ").expect("allow rule present");
        let deny_pos = out.find("deny ").expect("deny rule present");
        assert!(
            allow_pos < deny_pos,
            "allow must come before deny in miniupnpd.conf"
        );
    }

    /// Separate nftables table + chains isolate miniupnpd's transient
    /// mappings from the main oxwrt rules. Regression here (wrong
    /// option names, missing directives) means miniupnpd's DNATs
    /// would land in the wrong place and the main firewall reload
    /// would wipe them — or miniupnpd would refuse to start at all
    /// on "invalid option" in 2.3.x (which is exactly what happened
    /// during the 2026-04-20 audit before the rename).
    #[test]
    fn render_points_miniupnpd_at_separate_nftables_objects() {
        let out = render(&sample(), "00000000-0000-0000-0000-000000000001");
        assert!(out.contains("upnp_table_name=oxwrt-upnpd"));
        assert!(out.contains("upnp_nat_chain=prerouting_upnpd"));
        assert!(out.contains("upnp_nat_postrouting_chain=postrouting_upnpd"));
        assert!(out.contains("upnp_forward_chain=forward_upnpd"));
    }

    /// WAN iface with PPPoE-style name (contains special chars) —
    /// no escape-the-quote-type shell quoting should be applied to
    /// the ext_ifname line.
    #[test]
    fn render_passes_wan_name_through() {
        let mut c = sample();
        c.wan = "ppp0".into();
        let out = render(&c, "00000000-0000-0000-0000-000000000001");
        assert!(out.contains("ext_ifname=ppp0"));
    }

    // ── write_config I/O tests ─────────────────────────────────────

    /// write_config is a no-op when cfg.upnp is None. It must NOT
    /// delete a pre-existing config file — doing so would race the
    /// running miniupnpd service on a reload that toggles upnp off
    /// momentarily. Exercised via a minimal TOML config.
    #[test]
    fn write_config_is_noop_when_disabled() {
        let toml = r#"
hostname = "t"

[[networks]]
name = "lan"
type = "lan"
bridge = "br-lan"
address = "192.168.50.1"
prefix = 24

[control]
listen = ["[::1]:51820"]
authorized_keys = "/x"
"#;
        let cfg: Config = toml::from_str(toml).unwrap();
        assert!(cfg.upnp.is_none());
        // Should not error and should not attempt to write.
        assert!(write_config(&cfg).is_ok());
    }
}
