//! ntpd-rs config renderer — writes `/etc/oxwrt/ntp.toml` from
//! `[ntp]` in oxwrt.toml at boot + reload.
//!
//! Last of the three hand-edited-service-file holdouts (hickory +
//! coredhcp already absorbed). After this, DNS / DHCP / NTP all
//! derive from the single TOML pair on disk — no more "edit the
//! bind-mounted file under /usr/lib/oxwrt/services/" workflow.
//!
//! Unset `[ntp]` → no render; legacy bind-mount stays authoritative.

use std::fmt::Write as _;
use std::path::Path;

use oxwrt_api::config::{Config, NtpConfig, NtpSource};

use crate::net::Error;

const OUT_PATH: &str = "/etc/oxwrt/ntp.toml";

pub fn write_config(cfg: &Config) -> Result<(), Error> {
    let Some(ntp) = cfg.ntp.as_ref() else {
        return Ok(());
    };
    let text = render(ntp);
    if let Some(parent) = Path::new(OUT_PATH).parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| Error::Firewall(format!("ntpd: mkdir {parent:?}: {e}")))?;
    }
    std::fs::write(OUT_PATH, text)
        .map_err(|e| Error::Firewall(format!("ntpd: write {OUT_PATH}: {e}")))?;
    Ok(())
}

pub fn render(ntp: &NtpConfig) -> String {
    let mut s = String::new();
    writeln!(s, "# Auto-generated by oxwrtd ntpd::write_config.").unwrap();
    writeln!(s, "# Source of truth: /etc/oxwrt/oxwrt.toml [ntp] section.").unwrap();
    writeln!(s, "# Edit oxwrt.toml + `oxctl reload`, not this file.").unwrap();
    writeln!(s).unwrap();

    writeln!(s, "[source-defaults]").unwrap();
    writeln!(
        s,
        "poll-interval-limits = {{ min = {}, max = {} }}",
        ntp.poll_min, ntp.poll_max
    )
    .unwrap();
    writeln!(s).unwrap();

    for src in &ntp.sources {
        render_source(&mut s, src);
    }
    for addr in &ntp.listen {
        writeln!(s, "[[server]]").unwrap();
        writeln!(s, "listen = \"{addr}\"").unwrap();
        writeln!(s).unwrap();
    }
    s
}

fn render_source(s: &mut String, src: &NtpSource) {
    writeln!(s, "[[source]]").unwrap();
    writeln!(s, "mode = \"{}\"", src.mode).unwrap();
    writeln!(s, "address = \"{}\"", src.address).unwrap();
    if src.mode == "pool" {
        if let Some(n) = src.count {
            writeln!(s, "count = {n}").unwrap();
        }
    }
    writeln!(s).unwrap();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cfg_default_pool() -> NtpConfig {
        NtpConfig {
            sources: vec![NtpSource {
                mode: "pool".into(),
                address: "pool.ntp.org".into(),
                count: Some(4),
            }],
            listen: vec!["0.0.0.0:1123".into()],
            poll_min: 4,
            poll_max: 10,
        }
    }

    #[test]
    fn basic_pool_plus_server() {
        let text = render(&cfg_default_pool());
        assert!(text.contains("poll-interval-limits = { min = 4, max = 10 }"));
        assert!(text.contains("[[source]]"));
        assert!(text.contains("mode = \"pool\""));
        assert!(text.contains("address = \"pool.ntp.org\""));
        assert!(text.contains("count = 4"));
        assert!(text.contains("[[server]]"));
        assert!(text.contains("listen = \"0.0.0.0:1123\""));
    }

    #[test]
    fn server_mode_omits_count() {
        let mut cfg = cfg_default_pool();
        cfg.sources[0] = NtpSource {
            mode: "server".into(),
            address: "time.cloudflare.com".into(),
            count: Some(10), // should NOT render for server mode
        };
        let text = render(&cfg);
        assert!(text.contains("mode = \"server\""));
        assert!(text.contains("time.cloudflare.com"));
        assert!(
            !text.contains("count ="),
            "count must not render for server mode"
        );
    }

    #[test]
    fn no_listeners_no_server_block() {
        let mut cfg = cfg_default_pool();
        cfg.listen = vec![];
        let text = render(&cfg);
        assert!(!text.contains("[[server]]"));
    }

    #[test]
    fn empty_sources_still_valid() {
        let cfg = NtpConfig {
            sources: vec![],
            listen: vec!["127.0.0.1:123".into()],
            poll_min: 6,
            poll_max: 12,
        };
        let text = render(&cfg);
        assert!(text.contains("min = 6"));
        assert!(text.contains("max = 12"));
        assert!(!text.contains("[[source]]"));
    }
}
