//! Per-service resolv.conf renderer for isolated-netns services.
//!
//! Background: a supervised service running in its own netns
//! (`net_mode = "isolated"`) only sees its veth peer and its
//! gateway (the host-side veth end). When the service resolves a
//! domain name via libc's resolver, the query goes to whatever
//! `/etc/resolv.conf` inside the container rootfs says. Most
//! service rootfs tarballs don't ship a resolv.conf (image is
//! minimal by design), and even if they did, the target IP would
//! be wrong — there's no stable "router DNS IP" across deployments.
//!
//! This module writes a per-service resolv.conf containing a single
//! `nameserver <host_ip>` line (the veth gateway), to a host path
//! that `container::prepare` then bind-mounts into the service's
//! rootfs at `/etc/resolv.conf`. The firewall's DNS DNAT rule set
//! covers the host_ip so queries land at the `dns` service.
//!
//! Called from `reload` (as part of the regenerator chain alongside
//! coredhcp / corerad / ntpd / miniupnpd renderers) and at first
//! boot from `main_loop.rs` via the same path.
//!
//! Deliberately NOT a per-service config field in the schema — the
//! rendering is mechanical (one line per file), the operator never
//! needs to touch it, and the implicit bind in container::prepare
//! keeps the service.binds list declarative about the service's
//! own config files.

use std::io::Write;
use std::path::{Path, PathBuf};

use oxwrt_api::config::{Config, NetMode};

use crate::net::Error;

/// Directory where per-service resolv.conf files are rendered.
/// Under /etc/oxwrt/ so they're preserved across sysupgrade via
/// the standard keeplist. One file per isolated service, named
/// `<svc>.conf`.
pub const RESOLV_DIR: &str = "/etc/oxwrt/svc-resolv";

/// Host-side path for a service's resolv.conf. container::prepare
/// uses this as the bind source when setting up the implicit
/// `/etc/resolv.conf` inside isolated services.
pub fn host_path(svc_name: &str) -> PathBuf {
    PathBuf::from(RESOLV_DIR).join(format!("{svc_name}.conf"))
}

/// Render and write one resolv.conf per isolated service.
/// Idempotent: silently overwrites existing files (content is
/// a pure function of the veth host_ip).
pub fn write_all(cfg: &Config) -> Result<(), Error> {
    std::fs::create_dir_all(RESOLV_DIR).map_err(Error::Socket)?;
    for svc in &cfg.services {
        if svc.net_mode != NetMode::Isolated {
            continue;
        }
        let Some(veth) = &svc.veth else {
            continue;
        };
        let path = host_path(&svc.name);
        let contents = render(&veth.host_ip.to_string());
        atomic_write(&path, contents.as_bytes()).map_err(Error::Socket)?;
    }
    Ok(())
}

/// Pure function for unit tests. Format: one `nameserver` line
/// pointing at the veth gateway. The `options` line bounds
/// resolver retry time so a flaky upstream doesn't hang every
/// DNS-using syscall for 30+ seconds (glibc/musl default).
pub fn render(nameserver: &str) -> String {
    format!(
        "# Generated by oxwrtd svc_resolv::write_all — do not edit.\n\
         nameserver {nameserver}\n\
         options timeout:2 attempts:2\n",
    )
}

fn atomic_write(path: &Path, contents: &[u8]) -> std::io::Result<()> {
    let tmp = path.with_extension("tmp");
    {
        let mut f = std::fs::File::create(&tmp)?;
        f.write_all(contents)?;
        f.sync_all()?;
    }
    std::fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_includes_nameserver_and_options() {
        let out = render("10.123.0.1");
        assert!(out.contains("nameserver 10.123.0.1\n"), "{out}");
        assert!(out.contains("options timeout:2 attempts:2"), "{out}");
    }

    #[test]
    fn host_path_shapes_per_service() {
        assert_eq!(
            host_path("ntp"),
            PathBuf::from("/etc/oxwrt/svc-resolv/ntp.conf")
        );
        assert_eq!(
            host_path("dns"),
            PathBuf::from("/etc/oxwrt/svc-resolv/dns.conf")
        );
    }
}
